[hypo71] Fix arrival count measures
SeisComP/contrib-ipgp pull request #6
Opened 2023-12-22 12:35 UTC by gempa-dirk

2023-12-22 12:41 UTC, gempa-dirk commented
@jmsaurel Please comment the PR and allow us to merge it into master.

2024-01-26 09:49 UTC, jmsaurel commented
@gempa-dirk this PR looks ok for me.
I do not see anything obviously wrong or erroneous.

2024-01-31 07:09 UTC, gempa-jabe requested changes

2024-01-31 07:09 UTC, gempa-jabe commented on plugins/locator/hypo71/hypo71.cpp
> +					if ( sArrival->timeUsed() ) {
This can throw an exception.

2024-01-31 07:09 UTC, gempa-jabe commented on plugins/locator/hypo71/hypo71.cpp
> +					if ( pArrival->timeUsed() ) {
This can throw an exception.

2024-02-02 08:45 UTC, gempa-dirk commented on plugins/locator/hypo71/hypo71.cpp
> +					if ( sArrival->timeUsed() ) {
try ... catch added

2024-02-02 08:45 UTC, gempa-dirk commented on plugins/locator/hypo71/hypo71.cpp
> +					if ( pArrival->timeUsed() ) {
try ... catch added

2024-02-02 09:31 UTC, gempa-jabe requested changes

2024-02-02 09:31 UTC, gempa-jabe commented on plugins/locator/hypo71/hypo71.cpp
> +					} catch ( exception& e ) {
Newline before `catch`.

2024-02-02 09:31 UTC, gempa-jabe commented on plugins/locator/hypo71/hypo71.cpp
> +					} catch ( exception& e ) {
Newline

2024-02-02 10:51 UTC, gempa-dirk commented on plugins/locator/hypo71/hypo71.cpp
> +					} catch ( exception& e ) {
adjusted

2024-02-02 10:57 UTC, gempa-jabe approved these changes

2024-02-02 10:59 UTC, merged